language: java
jdk:
  - openjdk11

services:
  - docker

stages:
  - build
  - name: publish
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: build
      script: ./gradlew clean build jacocoTestReport codacyUpload
    - stage: publish
      script: ./gradlew clean build -Dbuild.number=$TRAVIS_BUILD_NUMBER
