language: node_js
node_js:
  - "10"

stages:
  - build
  - name: publish
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: build
      script: npm run build
    - stage: publish
      script: echo 'Not available'